// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? 'AIzaSyAY5Dd58cma28su-lErbDavyyqsAY7CZ34',
    appId: dotenv.env['FIREBASE_WEB_APP_ID'] ?? '1:632864778726:web:239254e42d1d2f857ece27',
    messagingSenderId: dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'] ?? '632864778726',
    projectId: dotenv.env['FIREBASE_WEB_PROJECT_ID'] ?? 'lg-tv-remotec',
    authDomain: dotenv.env['FIREBASE_WEB_AUTH_DOMAIN'] ?? 'lg-tv-remotec.firebaseapp.com',
    storageBucket: dotenv.env['FIREBASE_WEB_STORAGE_BUCKET'] ?? 'lg-tv-remotec.firebasestorage.app',
    measurementId: dotenv.env['FIREBASE_WEB_MEASUREMENT_ID'] ?? 'G-EC5BWZX0C3',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? 'AIzaSyCAn7p7cjD88x818upsp32bcvm1jpbnIp0',
    appId: dotenv.env['FIREBASE_ANDROID_APP_ID'] ?? '1:632864778726:android:e4297775ad19c5407ece27',
    messagingSenderId: dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'] ?? '632864778726',
    projectId: dotenv.env['FIREBASE_WEB_PROJECT_ID'] ?? 'lg-tv-remotec',
    storageBucket: dotenv.env['FIREBASE_ANDROID_STORAGE_BUCKET'] ?? 'lg-tv-remotec.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? 'AIzaSyB3ibP28NaLCg5SYTRpSKbey9T492ucSn4',
    appId: dotenv.env['FIREBASE_IOS_APP_ID'] ?? '1:632864778726:ios:b037eab112f008cb7ece27',
    messagingSenderId: dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'] ?? '632864778726',
    projectId: dotenv.env['FIREBASE_WEB_PROJECT_ID'] ?? 'lg-tv-remotec',
    storageBucket: dotenv.env['FIREBASE_IOS_STORAGE_BUCKET'] ?? 'lg-tv-remotec.firebasestorage.app',
    iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID'] ?? 'com.example.remoteControllerApp',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_MACOS_API_KEY'] ?? 'AIzaSyB3ibP28NaLCg5SYTRpSKbey9T492ucSn4',
    appId: dotenv.env['FIREBASE_MACOS_APP_ID'] ?? '1:632864778726:ios:b037eab112f008cb7ece27',
    messagingSenderId: dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'] ?? '632864778726',
    projectId: dotenv.env['FIREBASE_WEB_PROJECT_ID'] ?? 'lg-tv-remotec',
    storageBucket: dotenv.env['FIREBASE_MACOS_STORAGE_BUCKET'] ?? 'lg-tv-remotec.firebasestorage.app',
    iosBundleId: dotenv.env['FIREBASE_MACOS_BUNDLE_ID'] ?? 'com.example.remoteControllerApp',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WINDOWS_API_KEY'] ?? 'AIzaSyAY5Dd58cma28su-lErbDavyyqsAY7CZ34',
    appId: dotenv.env['FIREBASE_WINDOWS_APP_ID'] ?? '1:632864778726:web:28ad93ca727316f07ece27',
    messagingSenderId: dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'] ?? '632864778726',
    projectId: dotenv.env['FIREBASE_WEB_PROJECT_ID'] ?? 'lg-tv-remotec',
    authDomain: dotenv.env['FIREBASE_WINDOWS_AUTH_DOMAIN'] ?? 'lg-tv-remotec.firebaseapp.com',
    storageBucket: dotenv.env['FIREBASE_WINDOWS_STORAGE_BUCKET'] ?? 'lg-tv-remotec.firebasestorage.app',
    measurementId: dotenv.env['FIREBASE_WINDOWS_MEASUREMENT_ID'] ?? 'G-868EY0KT8V',
  );
}
