// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web {
    final apiKey = dotenv.env['FIREBASE_WEB_API_KEY'];
    final appId = dotenv.env['FIREBASE_WEB_APP_ID'];
    final messagingSenderId = dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'];
    final projectId = dotenv.env['FIREBASE_WEB_PROJECT_ID'];
    final authDomain = dotenv.env['FIREBASE_WEB_AUTH_DOMAIN'];
    final storageBucket = dotenv.env['FIREBASE_WEB_STORAGE_BUCKET'];
    final measurementId = dotenv.env['FIREBASE_WEB_MEASUREMENT_ID'];
    
    if (apiKey == null || appId == null || messagingSenderId == null || 
        projectId == null || authDomain == null || storageBucket == null) {
      throw Exception('Firebase 환경 변수가 설정되지 않았습니다. .env 파일을 확인하세요.');
    }
    
    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      authDomain: authDomain,
      storageBucket: storageBucket,
      measurementId: measurementId,
    );
  }

  static FirebaseOptions get android {
    final apiKey = dotenv.env['FIREBASE_ANDROID_API_KEY'];
    final appId = dotenv.env['FIREBASE_ANDROID_APP_ID'];
    final messagingSenderId = dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'];
    final projectId = dotenv.env['FIREBASE_WEB_PROJECT_ID'];
    final storageBucket = dotenv.env['FIREBASE_ANDROID_STORAGE_BUCKET'];
    
    if (apiKey == null || appId == null || messagingSenderId == null || 
        projectId == null || storageBucket == null) {
      throw Exception('Firebase 환경 변수가 설정되지 않았습니다. .env 파일을 확인하세요.');
    }
    
    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      storageBucket: storageBucket,
    );
  }

  static FirebaseOptions get ios {
    final apiKey = dotenv.env['FIREBASE_IOS_API_KEY'];
    final appId = dotenv.env['FIREBASE_IOS_APP_ID'];
    final messagingSenderId = dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'];
    final projectId = dotenv.env['FIREBASE_WEB_PROJECT_ID'];
    final storageBucket = dotenv.env['FIREBASE_IOS_STORAGE_BUCKET'];
    final iosBundleId = dotenv.env['FIREBASE_IOS_BUNDLE_ID'];
    
    if (apiKey == null || appId == null || messagingSenderId == null || 
        projectId == null || storageBucket == null || iosBundleId == null) {
      throw Exception('Firebase 환경 변수가 설정되지 않았습니다. .env 파일을 확인하세요.');
    }
    
    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      storageBucket: storageBucket,
      iosBundleId: iosBundleId,
    );
  }

  static FirebaseOptions get macos {
    final apiKey = dotenv.env['FIREBASE_MACOS_API_KEY'];
    final appId = dotenv.env['FIREBASE_MACOS_APP_ID'];
    final messagingSenderId = dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'];
    final projectId = dotenv.env['FIREBASE_WEB_PROJECT_ID'];
    final storageBucket = dotenv.env['FIREBASE_MACOS_STORAGE_BUCKET'];
    final iosBundleId = dotenv.env['FIREBASE_MACOS_BUNDLE_ID'];
    
    if (apiKey == null || appId == null || messagingSenderId == null || 
        projectId == null || storageBucket == null || iosBundleId == null) {
      throw Exception('Firebase 환경 변수가 설정되지 않았습니다. .env 파일을 확인하세요.');
    }
    
    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      storageBucket: storageBucket,
      iosBundleId: iosBundleId,
    );
  }

  static FirebaseOptions get windows {
    final apiKey = dotenv.env['FIREBASE_WINDOWS_API_KEY'];
    final appId = dotenv.env['FIREBASE_WINDOWS_APP_ID'];
    final messagingSenderId = dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'];
    final projectId = dotenv.env['FIREBASE_WEB_PROJECT_ID'];
    final authDomain = dotenv.env['FIREBASE_WINDOWS_AUTH_DOMAIN'];
    final storageBucket = dotenv.env['FIREBASE_WINDOWS_STORAGE_BUCKET'];
    final measurementId = dotenv.env['FIREBASE_WINDOWS_MEASUREMENT_ID'];
    
    if (apiKey == null || appId == null || messagingSenderId == null || 
        projectId == null || authDomain == null || storageBucket == null) {
      throw Exception('Firebase 환경 변수가 설정되지 않았습니다. .env 파일을 확인하세요.');
    }
    
    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      authDomain: authDomain,
      storageBucket: storageBucket,
      measurementId: measurementId,
    );
  }
}
